baseurl = "http://yourSiteHere"
languageCode = "en-us"
title = "Functional Macro"
disqusShortname = "functionalmacro"
pygmentsstyle = "monokai"

[params]
    sidebartitle = "Functional Macro"
    sidebartagline = "Functional programming for macroeconomists"

[[menu.main]]
    name = "Blog"
    url = "/post"


[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "http://www.twitter.com/spencerlyon2"
    identifier = "twitter"

[[menu.social]]
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://www.linkedin.com/profile/view?id=148582461&trk=nav_responsive_tab_profile_pic"
    identifier = "linkedin"

[[menu.footer]]
    name = "Blog"
    url = "/post"

[indexes]
   category = "categories"
   tag = "tags"
   series = "series"

[permalinks]
    post = "post/:year/:month/:day/:filename/"
